### ISSUE TITLE
0705.txt 第八段出現火星文

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Hap-sing_Bun-pun#10]
原稿
Cha-bou2 gin2-a2 oat8-thau5 koe3-lai5, iong7 **1 e5** chin thian-chin koh long7-ban7 e5 chhio3-iong5 ka7 in3
翻寫漢羅
查某囡仔越頭過來，用**1的**真天真閣浪漫的笑容共應

被打敗了...我直接修成「用伊的」

**Comment by naphing** [comment]
第10段也有 1 ê，
第8段是我判斷錯誤，皆修正成tsit8 e5/一个

**Comment by sih4sing5hong5** [comment]
好，無問題
