### ISSUE TITLE
`a2 bo5` ? `ah8 bo5`?

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#15]
#17

@naphing 我對這無語感，麻煩你解說一下~~
原文
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/blob/master/tsingli/leku-0612.txt#L7
改好
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/blob/master/tsingli/leku-0612-hanlo.txt#L6

相關資料：http://ip194097.ntcu.edu.tw/TG/Concordance/concordance.asp?hp=poj&su=a2-bo5
https://chhoe.taigi.info/TaibunHoabunSoanntengSutian/2

**Comment by sih4sing5hong5** [comment]
原文圖：http://ip194097.ntcu.edu.tw/memory/tgb/thak.asp?id=929&page=10

**Comment by naphing** [comment]
我感覺是腔口差呢，嘛有可能是一開始白話字就寫毋著，積非成是
a2 bo5 = ah8 bo5 = 抑 無（參連寫的ah8-bo：不然，意思無仝）
a2、ah4、ah8 抑「還是」的意思
用英語來比就是「... or not」

**Comment by sih4sing5hong5** [comment]
來問看覓好--ah

![2019-03-08 13-36-02](https://user-images.githubusercontent.com/5996555/54009793-281f6200-41a7-11e9-9bc7-9e239879bf61.png)

**Comment by sih4sing5hong5** [comment]
有老師回--a
伊講教典有收書寫`ah`，毋過口語唸第1調，所以臆in用再變調解說

詞目 | 抑  			
-- | --
音讀 | ia̍h　又唸作iah、a̍h、ah

https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=3217&curpage=1&sample=ah4&radiobutton=0&querytarget=1&limit=20&pagenum=1&rowcount=6&fbclid=IwAR1fcBcneRX0gU1kZ7jd34cDMvcsuxsAMDzvLX44cyo8DHZ638jTjM4CA7E

**Comment by sih4sing5hong5** [comment]
教典有收第4調ê[抑無 ah-bó](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=13698&curpage=1&sample=%E6%8A%91%E7%84%A1&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1)

**Comment by sih4sing5hong5** [comment]
結論：作者寫第2調應該是想beh表達ê第1調口語調，照伊ê 想法揀對應教典ê書寫`抑無 ah-bó`

**Comment by sih4sing5hong5** [comment]
#28 修--ah
