### ISSUE TITLE
e1-am3 ? e7-am3?

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#18]
#17 
原文`e7-am3`

教典收`e1-am3`，臺日收`e7-am3`

**Comment by naphing** [comment]
教典：e1-am3 暗時
臺日：e7-am3 後日的暗時（意思不太一樣？）
e/e7都有[潘科元文章](https://blog.xuite.net/khoguan/blog/41048218)
教典方言差，[馬公欄](https://twblg.dict.edu.tw/holodict_new/cuankho.jsp?no=0220)

結論：e1跟e7都存在

**Comment by sih4sing5hong5** [comment]
多謝你查~~

按呢照原稿~~

**Comment by sih4sing5hong5** [comment]
#28 修--ah
