### ISSUE TITLE
0612  ê 文章名

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#19]
#17 
是講 `un-gian.pdf` 有文章名ê羅馬字
Kah @naphing ê 無kâng。

因為 https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/issues/6#issuecomment-470812531 leh改，所以莫直接改檔案，較袂conflict

**Comment by naphing** [comment]
用leku-0612.txt檔案落去排版，檔案裡就已經有**篇名+作者+年份**但是無羅馬字，
我攏保留而且加補羅馬字入去
頭兩篇 東部傳道見聞錄 閣加「著」字，致使核對篇名無仝？

**Comment by sih4sing5hong5** [comment]
頭前是這馬ê版本，後壁ê參考論文kah `tbk/`
- `Sin-bûn ê tsa̍p-li̍k` / `Sin-bûn ê tsa̍p-lio̍k`
- `Tsa̍p hāng kuán-kìnn` / `Tsa̍p-hāng kuán-kiàn`
- `Tshuà Puē-hué` / `Tshuà Puê-hué`

其他
`草堆頂的眠夢 兒童宗教故事` => `草堆頂的眠夢──兒童宗教故事`

**Comment by naphing** [comment]
Naphing跪著回應：
因為我偷懶直接貼到鬥拍字翻臺羅再COPY回來Orz
沒考慮到去查原始文章的寫法，對不起，我罰喝三杯嘎逼謝罪

> 頭前是這馬ê版本，後壁ê參考論文kah `tbk/`
> 
> * `Sin-bûn ê tsa̍p-li̍k` / `Sin-bûn ê tsa̍p-lio̍k`
> * `Tsa̍p hāng kuán-kìnn` / `Tsa̍p-hāng kuán-kiàn`
> * `Tshuà Puē-hué` / `Tshuà Puê-hué`
> 
沒特別注意「──」的存在
原txt檔沒有，我就沒補上
> 其他
> `草堆頂的眠夢 兒童宗教故事` => `草堆頂的眠夢──兒童宗教故事`
