### ISSUE TITLE
請tuà teh

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#21]
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/issues/8#issue-417693966

> 「你的查某囝若欲請tuà teh過一禮拜亦通。」
“Lí ê tsa-bóo-kiánn nā beh tshiánn tuà teh kè tsi̍t lé-pài ia̍h thang.”
「請蹛咧」？

原文意思是：恁tsa̋u囝若beh請假一禮拜嘛會saih.

是講恁敢有` V + teh過 + 時間` ê語感？

**Comment by sih4sing5hong5** [comment]
應該是校對過ê詞性
```
"Li2(R) e5(M) cha-bou2-kiann2#(N) na7(C) beh$(D) chhiann2(V) toa3(V) teh$(P) ke3(V) chit8(N) le2-pai3#(N) iah8(D) thang#(D)."
```

**Comment by naphing** [comment]
> [#8 (comment)](https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/issues/8#issue-417693966)
> 
> > 「你的查某囝若欲請tuà teh過一禮拜亦通。」
> > “Lí ê tsa-bóo-kiánn nā beh tshiánn tuà teh kè tsi̍t lé-pài ia̍h thang.”
> > 「請蹛咧」？
> 
> 原文意思是：恁tsa̋u囝若beh請假一禮拜嘛會saih.
> 
> 是講恁敢有` V + teh過 + 時間` ê語感？

NO...遇到這種詭異句子我都當他是教會的風格XDDDD

**Comment by sih4sing5hong5** [comment]
先照原稿，漢字才閣講

**Comment by sih4sing5hong5** [comment]
教會相關ê語料
```
   366	jit8-tsi2 teh4 kue3 m7-na7 kan1-khoo2 koh4 thua1-bua5 .
   367	sing1-uah8 si7 khoo2-khoo2-a2 teh4 kue3 .
   368	koh4 u7 tsin1 tse7 lang5 pai5-liat8 teh4 kue3 ping5-an1-kio5 ,
   369	lan2 e5 sing1-uah8 si7 lan2 teh4 kue3 ,
   370	si5-kan1 teh4 kue3 tsin1 kin2 ,
   371	tak8-kang1 bo5-huan5 bo5-lo2 teh4 kue3 jit8-tsi2 ?
   372	si5-kan1 teh4 kue3 sit8-tsai7 tsin1 kin2 ,
   373	gin2-a2-lang5 han2-tit4 teh4 kue3 senn1-jit8 ,
```

**Comment by naphing** [comment]
相關語料的 teh kue3 跟 V+teh kue3 無仝咧，我順過都成立阿XD

**Comment by sih4sing5hong5** [comment]
按呢老師斷句應該是佗一ê？

1. `你的查某囝若欲請` + `tuà teh過一禮拜亦通。`
1. `你的查某囝若欲請tuà` + `teh過一禮拜亦通。`
1. `你的查某囝若欲請tuà teh` + `過一禮拜亦通。`
1. `你的查某囝若欲請tuà teh過` + `一禮拜亦通。`

感覺是1,3其中一ê

[口語調資訊](https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/issues/21#issuecomment-470818282)：(`#`代表本調)
```
你的查某囝# 若欲請tuà teh過一禮拜# 亦通#。
```
`欲`kah`teh`是口語調第1掉ê`再變調`

**Comment by naphing** [comment]
找到原文圖檔 是toa3-teh ，應該是「咧」teh/leh
![4b33334755ec2](https://user-images.githubusercontent.com/35830498/54025858-cf67bd80-41d6-11e9-9e0a-79e554434a27.jpg)

**Comment by sih4sing5hong5** [comment]
> 找到原文圖檔 是toa3-teh ，應該是「咧」teh/leh

這敢有網站thang直接連過看？

**Comment by sih4sing5hong5** [comment]
揣著--ah
http://pojbh.lib.ntnu.edu.tw/script/src-3311.htm

**Comment by sih4sing5hong5** [comment]
> 按呢老師斷句應該是佗一ê？
> 
>     1. `你的查某囝若欲請` + `tuà teh過一禮拜亦通。`
> 
>     2. `你的查某囝若欲請tuà` + `teh過一禮拜亦通。`
> 
>     3. `你的查某囝若欲請tuà teh` + `過一禮拜亦通。`
> 
>     4. `你的查某囝若欲請tuà teh過` + `一禮拜亦通。`
> 
> 
> 感覺是1,3其中一ê
> 
> [口語調資訊](https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/issues/21#issuecomment-470818282)：(`#`代表本調)
> 
> ```
> 你的查某囝# 若欲請tuà teh過一禮拜# 亦通#。
> ```
> 
> `欲`kah`teh`是口語調第1掉ê`再變調`

需要知影斷句

**Comment by sih4sing5hong5** [comment]
開會結論：3斷句可能較好

**Comment by sih4sing5hong5** [comment]
結論：稿先按呢，漢字等網站系統才來改
