### ISSUE TITLE
總是 敢有無輕聲ê講法？

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#40]
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/blob/master/tsingli/leku-0612-hanlo.txt#L29
有3位`總是`

教典收`tsóng--sī`，
毋過文本攏是`tsóng-sī`，`sī`唸變調。

是文本無寫著輕聲，抑是實際有有無輕聲ê腔口？

**Comment by naphing** [comment]
張裕宏小詞典p.124有chong2-si7，也有chong2--si7--a2
個人語感也是有人念一般變調

**Comment by sih4sing5hong5** [comment]
> 張裕宏小詞典p.124有chong2-si7，也有chong2--si7--a2
> 個人語感也是有人念一般變調

好，TJ 有參考價值~

**Comment by sih4sing5hong5** [comment]
Tang-pō͘ thôan-tō kiàn-bûn-kì (東部傳道見聞記) Tân Kàng-siông (陳降祥) 1961 
有[chhia--ê](http://ip194097.ntcu.edu.tw/memory/tgb/thak.asp?id=929&page=30)

**Comment by sih4sing5hong5** [comment]
0612-2 東部傳道見聞記
```
總是後山#塗#真黏#，」
```
0612-6
```
總是我真毋愛#，
```
0705-3
```
總是8月30#號#佇華太島西爿岸#，
```

**Comment by sih4sing5hong5** [comment]
就照原稿
