### ISSUE TITLE
後來 敢有無輕聲ê講法？

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#42]
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/blob/master/tsingli/leku-0705-hanlo.txt#L35

### 教典寫`āu--lâi` 
- https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=4951&curpage=1&sample=+%E5%BE%8C%E4%BE%86&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=1

### 文本寫` Au7-lai5#(S) khi3$(V) Sio2-ke-lang&-a2(N) ...` 
https://github.com/Sui-Siann-Dataset/Hap-sing_Bun-pun/blob/master/tsingli/leku-0705-mark.txt#L35

**Comment by naphing** [comment]
張裕宏小詞典p.13有au7-lai5，意思是「將來」
個人語感是不會念一般變調（假設這个作者吃到華語喙瀾，無意識「後來」愛輕聲）

**Comment by sih4sing5hong5** [comment]
> 張裕宏小詞典p.13有au7-lai5，意思是「將來」
> 個人語感是不會念一般變調（假設這个作者吃到華語喙瀾，無意識「後來」愛輕聲）

因為 #49 ，我臆這篇原本應該是漢羅文
所以咱應該就ē-tàng改掉

**Comment by sih4sing5hong5** [comment]
已經改--ah
