### ISSUE TITLE
Nā-sī ê 漢字

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#47]
0705-5 出現2擺
```
我一時#ka-kī #感覺十#分#的歹勢#。心肝鼓噗噗惝#，面#tsiū 發烘#，大概#kánn 有紅紅#。
但是伊顛倒#是真大方#hāitsāi#。我一時#雖然#是真歹勢#，
m̄-kú一見#對這#个女性若準#佇sím-mi̍h 所在#捌#看伊的面#，而且是真熟#，宛如#早捌sann-bat (相捌)#的款式#。
但是這時#較#想都想不出#伊的名#。
```

這馬文章是`但是`，意思有合，毋過感覺怪怪

**Comment by sih4sing5hong5** [comment]
白話字 | 教育部羅馬字 | 漢羅台文(白話字) | 漢羅台文解說(白話字) |  
-- | -- | -- | -- | --
nā-sī | nā-sī | [但是] | 獨獨, 干但。 | [詳細](https://chhoe.taigi.info/TaiJitToaSuTian/41805)
nā-sī | nā-sī | [若是] | 如果，假使。| [詳細](https://chhoe.taigi.info/TaiJitToaSuTian/41806)

**Comment by naphing** [comment]
因為「但」有na7音，毋但m7-na7
猜作者可能先擬華語稿再轉的，所以出現「但na7是」？

**Comment by sih4sing5hong5** [comment]
> 因為「但」有na7音，毋但m7-na7
> 猜作者可能先擬華語稿再轉的，所以出現「但na7是」？

[作者](https://zh.wikipedia.org/wiki/%E8%B3%B4%E4%BB%81%E8%81%B2)是台灣人
作品是1955年
敢有可能先寫漢字稿 XD

是講咱就用臺日`獨獨, 干但。`ê 解說？

> 毋但m7-na7
`na7` 敢有別ê用法?

敢ē-tàng講 `m7-na7`=`put-tsi2`, 所以 `na7`=`tsi2`,

**Comment by naphing** [comment]
疑？這篇是賴仁聲的？賴仁聲的白話字小說用詞後期有受華語影響
但我無法確定na7-si7是不是華語來，我來查其他白話字文學作品看有沒有類似狀況

**Comment by naphing** [comment]
確定不是華語影響（自己婊自己）
1886年教會公報文章「論白話字ê利益」、「諫諍迎佛骨ê表」有這个詞，
當tú仔teh讀ê 時 m̄ 敢想會bat，**但是**到尾攏會家己讀，m̄ 免定定倚靠別人來教。
tng tú-á teh-tha̍k ê sî m̄-káⁿ siūⁿ ē bat, **nā-sī** kàu-boé lóng ē ka-tī tha̍k, m̄-bián tiāⁿ-tiāⁿ oá-khò pa̍t-lâng lâi kà .
Hit時天下太平，百姓平安快樂長歲壽；**但是**中國iáu-boē bat有佛。
Hit-sî thiⁿ-ē thài-pêng, peh-sèⁿ pêng-an khoài-lo̍k tn̂g hoè-siū; **nā-sī** Tiong-kok iáu-boē bat ū pu̍t.

**Comment by sih4sing5hong5** [comment]
按呢就照教育部用`但`
