### ISSUE TITLE
輕聲連字符，對啥物年代開始有人用？

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Hap-sing_Bun-pun#53]
#40 #42

一開始公報敢若攏無`--`
`tsóng--sī`, `āu--jit`, `khui--khui`,...

是tang-sî開始出現ê？
到tang-sî逐家一定會寫？

**Comment by naphing** [comment]
翻一下張裕宏「白話字基本論」看有沒有提，我只知道最早白話字進入中國福建一帶是麥都思做了本福建方言字典1837年，是給傳教士學習用。

**Comment by sih4sing5hong5** [comment]
> 翻一下張裕宏「白話字基本論」看有沒有提，我只知道最早白話字進入中國福建一帶是麥都思做了本福建方言字典1837年，是給傳教士學習用。

好，隨掀

**Comment by sih4sing5hong5** [comment]
`白話字基本論`無寫歷史，按呢我才閣看遐ê原文圖

**Comment by sih4sing5hong5** [comment]
[ Tâi-ôan Kàu-hōe Kong-pò(台灣教會公報)247期 台灣教會公報社 1905 ](http://ip194097.ntcu.edu.tw/Memory/TGB/thak.asp?id=364&page=8)有`sin-si--ê`, `hiah--nih`, `thâi--lo̍h-khì`,
