### ISSUE TITLE
論文篇名愛留無？

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Hap-sing_Bun-pun#6]
原檔leku-0612.txt內底的篇名無羅馬字，Naphing整理leku-0612-hanlo.txt會補羅馬字

**Comment by sih4sing5hong5** [comment]
看 #12 ê 結果，
若是字數袂準，就攏先錄--起來。

**Comment by a8568730** [comment]
結論：
因為 PR #14 發覺允言統計的字數無包括篇名，所以為著咱方便統計字數，
會共naphing整理的論文篇名會做新的一逝，干焦唸一遍。

親像：
1.
「恁kiám無講，猶有四月日，就收割的時到嘛？我共恁講，kia̍h目看園已經熟，通割啦。」
“Lín kiám bô kóng, iáu ū sì ge̍h ji̍t, tsiū siu-kuah ê sî kàu--mah? Guá kā lín kóng, kia̍h-ba̍k khuànn hn̂g í-king si̍k, thang kuah--lah.”

2.
我若問遐的兄弟講。「恁有想欲閣轉來西部抑無？」𪜶講：「想是會想，總是後山塗真黏，」意思是行袂開腳，因為好趁食，呔有影後山的塗有黏咧？
Guá nā mn̄g hia ê hiann-tī kóng, “Lín ū siūnn-beh koh tńg-lâi se-pōo a̍h bô?” In kóng, “Siūnn sī ē siūnn, tsóng--sī āu-suann thôo tsin liâm,” ì-sù sī kiânn buē khui-kha, in-uī hó thàn-tsia̍h, thài ū-iánn āu-suann ê thôo ū liâm--leh?

東部傳道見聞記 陳降祥 著1961
Tang-pōo thuân-tō kiàn-bûn-kì Tân Kàng-siông tù it kiú lio̍k it
