### ISSUE TITLE
0612-hanlo一寡拼音佮漢字欲改無？

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Hap-sing_Bun-pun#8]
無原件通參考，幾位感覺怪怪，看欲改無
1.
恁**kiám**無講 
可能是[敢](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=14367&curpage=1&sample=%E6%95%A2%E6%98%AF&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=2)
**kia̍h**目看園已經熟
可能是[攑gia̍h](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=13120&curpage=1&sample=giah8&radiobutton=1&querytarget=1&limit=20&pagenum=2&rowcount=33)
5.
有拄著一个細漢囡仔**兇兇**走竄過--去。
ū tú-tio̍h tsi̍t ê suè-hàn gín-ná **hiong-hiong** tsáu tshuàn kè--khì.
是雄雄？
6.
看伊的款式親像知伊**亦**有毋著。
khuànn i ê khuán-sit tshin-tshiūnn tsai i **ia̍h** ū m̄-tio̍h.
要改「也iā」嗎？
「你的查某囝若欲**請tuà teh**過一禮拜**亦**通。」
“Lí ê tsa-bóo-kiánn nā beh **tshiánn tuà teh** kè tsi̍t lé-pài **ia̍h** thang.”
「請蹛咧」？

**Comment by sih4sing5hong5** [comment]
感謝@naphing 頂真整理，確實攏愛討論。
後擺這5條就做5 ê issue，討論較袂花--去 XD

> 無原件通參考，幾位感覺怪怪，看欲改無
> 1.
> 恁**kiám**無講
> 可能是[敢](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=14367&curpage=1&sample=%E6%95%A2%E6%98%AF&radiobutton=1&querytarget=1&limit=20&pagenum=1&rowcount=2)

是，tsiânn tsē人按呢用。
結論：文稿保持kiám予老師唸，網站時才閣改漢字。

> **kia̍h**目看園已經熟
> 可能是[攑gia̍h](https://twblg.dict.edu.tw/holodict_new/result_detail.jsp?n_no=13120&curpage=1&sample=giah8&radiobutton=1&querytarget=1&limit=20&pagenum=2&rowcount=33)

[台華](https://chhoe.taigi.info/TaibunHoabunSoanntengSutian/40447)有收`kia̍h-ba̍k`
google`kia̍h目`嘛袂少古早文按呢寫
是講[蘇老師 2016 ê 教會im-ga̍k](https://www.youtube.com/watch?v=kGN8psev7V8)寫`gia̍h-ba̍k`，
應該伊較準。

結論：改gia̍h-ba̍k`

> 5.
> 有拄著一个細漢囡仔**兇兇**走竄過--去。
> ū tú-tio̍h tsi̍t ê suè-hàn gín-ná **hiong-hiong** tsáu tshuàn kè--khì.
> 是雄雄？

[臺日](https://chhoe.taigi.info/TaiJitToaSuTian/19808)有收`兇兇`，意思有合原文

教育部羅馬字 | 漢羅台文(白話字) | 漢羅台文解說(白話字)
-- | -- | --
hiong-hiong | [兇兇] | (1)污穢。 (2)慌忙。




> 6.
> 看伊的款式親像知伊**亦**有毋著。
> khuànn i ê khuán-sit tshin-tshiūnn tsai i **ia̍h** ū m̄-tio̍h.
> 要改「也iā」嗎？
> 「你的查某囝若欲**請tuà teh**過一禮拜**亦**通。」
> “Lí ê tsa-bóo-kiánn nā beh **tshiánn tuà teh** kè tsi̍t lé-pài **ia̍h** thang.”
> 「請蹛咧」？

原文：http://ip194097.ntcu.edu.tw/nmtl/dadwt/thak.asp?id=309
我先查一下

**Comment by sih4sing5hong5** [comment]
> 6.
> 看伊的款式親像知伊**亦**有毋著。
> khuànn i ê khuán-sit tshin-tshiūnn tsai i **ia̍h** ū m̄-tio̍h.
> 「你的查某囝若欲**請tuà teh**過一禮拜**亦**通。」
> “Lí ê tsa-bóo-kiánn nā beh **tshiánn tuà teh** kè tsi̍t lé-pài **ia̍h** thang.”
> 要改「也iā」嗎？

好，改 `iā`。等 #14 merge 才來改

> 「請蹛咧」？

#21 討論
