### ISSUE TITLE
leku-0612.txt第八條原文字數不符

### ISSUE THREAD

**Issue by naphing** [Sui-Siann-Dataset/Hap-sing_Bun-pun#9]
第八條十項管見原文字數不符
將來若是**koh** 用心加人e5 工夫大大來整頓
chiong-lai5 na7-si7 eng7-sim ke lang5 e5 kang-hu toa7-toa7 lai5 cheng2-tun3

漢字多個koh，0612-hanlo.txt刪除漢字

**Comment by naphing** [comment]
第八條原文字數不符
愛山就有山、**愛海就海**
ai3 soaN chiu7 u7 soaN , **ai3 hai2 chiu7 u7 hai2**
0612-han-lo補漢字「有」

**Comment by sih4sing5hong5** [comment]
> 第八條十項管見原文字數不符
> 將來若是**koh** 用心加人e5 工夫大大來整頓
> chiong-lai5 na7-si7 eng7-sim ke lang5 e5 kang-hu toa7-toa7 lai5 cheng2-tun3
> 
> 漢字多個koh，0612-hanlo.txt刪除漢字

原文漢羅攏有koh
http://ip194097.ntcu.edu.tw/nmtl/dadwt/thak.asp?id=314

我想一下beh 按怎較好

**Comment by sih4sing5hong5** [comment]
> 第八條原文字數不符
> 愛山就有山、**愛海就海**
> ai3 soaN chiu7 u7 soaN , **ai3 hai2 chiu7 u7 hai2**
> 0612-han-lo補漢字「有」

http://ip194097.ntcu.edu.tw/nmtl/dadwt/thak.asp?id=314
原文有`有` OK

**Comment by sih4sing5hong5** [comment]
> > 第八條原文字數不符
> > 愛山就有山、**愛海就海**
> > ai3 soaN chiu7 u7 soaN , **ai3 hai2 chiu7 u7 hai2**
> > 0612-han-lo補漢字「有」
> 
> http://ip194097.ntcu.edu.tw/nmtl/dadwt/thak.asp?id=314
> 原文有`有` OK

查tòo-tôo無 `ū`，照頂下文應該愛加較有理，因為另外3句攏是`...就有...`
結論：加`有`

**Comment by sih4sing5hong5** [comment]
> 第八條十項管見原文字數不符
> 將來若是**koh** 用心加人e5 工夫大大來整頓
> chiong-lai5 na7-si7 eng7-sim ke lang5 e5 kang-hu toa7-toa7 lai5 cheng2-tun3
> 
> 漢字多個koh，0612-hanlo.txt刪除漢字

原文有`koh`

![2019-03-09 13-02-45 的螢幕擷圖](https://user-images.githubusercontent.com/5996555/54066477-ab09f080-426b-11e9-9180-1fdc0988f281.png)
http://ip194097.ntcu.edu.tw/Memory/TGB/thak.asp?id=881&page=11

結論：加`koh`

**Comment by sih4sing5hong5** [comment]
多謝 @naphing 揣出問題~~
改好--ah
